// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bid_meta_entity.proto

package com.example.dto;

public final class BidMetaEntity {
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidMetaEntityMessage_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internal_static_BidMetaEntityMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
    descriptor;

  static {
    String[] descriptorData = {
      "\n\025bid_meta_entity.proto\032\016dmp_intf.proto\"" +
        "\317\001\n\024BidMetaEntityMessage\022\032\n\010tld_info\030\001 \001" +
        "(\0132\010.TldInfo\022\032\n\010nld_info\030\002 \001(\0132\010.NldInfo" +
        "\022\034\n\tpage_info\030\003 \001(\0132\t.PageInfo\022\032\n\010app_in" +
        "fo\030\004 \001(\0132\010.AppInfo\022\026\n\016transaction_id\030\005 \001" +
        "(\004\022\032\n\022source_instance_id\030\006 \001(\004\022\021\n\ttimest" +
        "amp\030\007 \001(\004B+\n\037com.cinarra.bidpersister.do" +
        "mainZ\010cnrproto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
          com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.dto.DmpIntf.getDescriptor(),
        }, assigner);
    internal_static_BidMetaEntityMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BidMetaEntityMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
      internal_static_BidMetaEntityMessage_descriptor,
      new String[] {
        "TldInfo", "NldInfo", "PageInfo", "AppInfo", "TransactionId", "SourceInstanceId",
        "Timestamp",});
    com.example.dto.DmpIntf.getDescriptor();
  }

  private BidMetaEntity() {}

  public static void registerAllExtensions(
    com.google.protobuf.ExtensionRegistry registry) {
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  public interface BidMetaEntityMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BidMetaEntityMessage)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .TldInfo tld_info = 1;</code>
     */
    boolean hasTldInfo();

    /**
     * <code>optional .TldInfo tld_info = 1;</code>
     */
    com.example.dto.DmpIntf.TldInfo getTldInfo();

    /**
     * <code>optional .TldInfo tld_info = 1;</code>
     */
    com.example.dto.DmpIntf.TldInfoOrBuilder getTldInfoOrBuilder();

    /**
     * <code>optional .NldInfo nld_info = 2;</code>
     */
    boolean hasNldInfo();

    /**
     * <code>optional .NldInfo nld_info = 2;</code>
     */
    com.example.dto.DmpIntf.NldInfo getNldInfo();

    /**
     * <code>optional .NldInfo nld_info = 2;</code>
     */
    com.example.dto.DmpIntf.NldInfoOrBuilder getNldInfoOrBuilder();

    /**
     * <code>optional .PageInfo page_info = 3;</code>
     */
    boolean hasPageInfo();

    /**
     * <code>optional .PageInfo page_info = 3;</code>
     */
    com.example.dto.DmpIntf.PageInfo getPageInfo();

    /**
     * <code>optional .PageInfo page_info = 3;</code>
     */
    com.example.dto.DmpIntf.PageInfoOrBuilder getPageInfoOrBuilder();

    /**
     * <code>optional .AppInfo app_info = 4;</code>
     */
    boolean hasAppInfo();

    /**
     * <code>optional .AppInfo app_info = 4;</code>
     */
    com.example.dto.DmpIntf.AppInfo getAppInfo();

    /**
     * <code>optional .AppInfo app_info = 4;</code>
     */
    com.example.dto.DmpIntf.AppInfoOrBuilder getAppInfoOrBuilder();

    /**
     * <code>optional uint64 transaction_id = 5;</code>
     */
    boolean hasTransactionId();

    /**
     * <code>optional uint64 transaction_id = 5;</code>
     */
    long getTransactionId();

    /**
     * <code>optional uint64 source_instance_id = 6;</code>
     */
    boolean hasSourceInstanceId();

    /**
     * <code>optional uint64 source_instance_id = 6;</code>
     */
    long getSourceInstanceId();

    /**
     * <code>optional uint64 timestamp = 7;</code>
     */
    boolean hasTimestamp();

    /**
     * <code>optional uint64 timestamp = 7;</code>
     */
    long getTimestamp();
  }

  /**
   * Protobuf type {@code BidMetaEntityMessage}
   */
  public static final class BidMetaEntityMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:BidMetaEntityMessage)
    BidMetaEntityMessageOrBuilder {
    public static final int TLD_INFO_FIELD_NUMBER = 1;
    public static final int NLD_INFO_FIELD_NUMBER = 2;
    public static final int PAGE_INFO_FIELD_NUMBER = 3;
    public static final int APP_INFO_FIELD_NUMBER = 4;
    public static final int TRANSACTION_ID_FIELD_NUMBER = 5;
    public static final int SOURCE_INSTANCE_ID_FIELD_NUMBER = 6;
    public static final int TIMESTAMP_FIELD_NUMBER = 7;
    private static final BidMetaEntityMessage defaultInstance;
    private static final long serialVersionUID = 0L;
    public static com.google.protobuf.Parser<BidMetaEntityMessage> PARSER =
      new com.google.protobuf.AbstractParser<BidMetaEntityMessage>() {
        public BidMetaEntityMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BidMetaEntityMessage(input, extensionRegistry);
        }
      };

    static {
      defaultInstance = new BidMetaEntityMessage(true);
      defaultInstance.initFields();
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    private int bitField0_;
    private com.example.dto.DmpIntf.TldInfo tldInfo_;
    private com.example.dto.DmpIntf.NldInfo nldInfo_;
    private com.example.dto.DmpIntf.PageInfo pageInfo_;
    private com.example.dto.DmpIntf.AppInfo appInfo_;
    private long transactionId_;
    private long sourceInstanceId_;
    private long timestamp_;
    private byte memoizedIsInitialized = -1;
    private int memoizedSerializedSize = -1;

    // Use BidMetaEntityMessage.newBuilder() to construct.
    private BidMetaEntityMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }

    private BidMetaEntityMessage(boolean noInit) {
      this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BidMetaEntityMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.example.dto.DmpIntf.TldInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = tldInfo_.toBuilder();
              }
              tldInfo_ = input.readMessage(
                com.example.dto.DmpIntf.TldInfo.PARSER,
                extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(tldInfo_);
                tldInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.example.dto.DmpIntf.NldInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = nldInfo_.toBuilder();
              }
              nldInfo_ = input.readMessage(
                com.example.dto.DmpIntf.NldInfo.PARSER,
                extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(nldInfo_);
                nldInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.example.dto.DmpIntf.PageInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = pageInfo_.toBuilder();
              }
              pageInfo_ = input.readMessage(
                com.example.dto.DmpIntf.PageInfo.PARSER,
                extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pageInfo_);
                pageInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              com.example.dto.DmpIntf.AppInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = appInfo_.toBuilder();
              }
              appInfo_ = input.readMessage(
                com.example.dto.DmpIntf.AppInfo.PARSER,
                extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(appInfo_);
                appInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              transactionId_ = input.readUInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              sourceInstanceId_ = input.readUInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              timestamp_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static BidMetaEntityMessage getDefaultInstance() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return BidMetaEntity.internal_static_BidMetaEntityMessage_descriptor;
    }

    public static BidMetaEntityMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static BidMetaEntityMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static BidMetaEntityMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static BidMetaEntityMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static BidMetaEntityMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static BidMetaEntityMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static BidMetaEntityMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }

    public static BidMetaEntityMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static BidMetaEntityMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static BidMetaEntityMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }

    public static Builder newBuilder(BidMetaEntityMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }

    public BidMetaEntityMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return BidMetaEntity.internal_static_BidMetaEntityMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
          BidMetaEntityMessage.class, Builder.class);
    }

    @Override
    public com.google.protobuf.Parser<BidMetaEntityMessage> getParserForType() {
      return PARSER;
    }

    /**
     * <code>optional .TldInfo tld_info = 1;</code>
     */
    public boolean hasTldInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }

    /**
     * <code>optional .TldInfo tld_info = 1;</code>
     */
    public com.example.dto.DmpIntf.TldInfo getTldInfo() {
      return tldInfo_;
    }

    /**
     * <code>optional .TldInfo tld_info = 1;</code>
     */
    public com.example.dto.DmpIntf.TldInfoOrBuilder getTldInfoOrBuilder() {
      return tldInfo_;
    }

    /**
     * <code>optional .NldInfo nld_info = 2;</code>
     */
    public boolean hasNldInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }

    /**
     * <code>optional .NldInfo nld_info = 2;</code>
     */
    public com.example.dto.DmpIntf.NldInfo getNldInfo() {
      return nldInfo_;
    }

    /**
     * <code>optional .NldInfo nld_info = 2;</code>
     */
    public com.example.dto.DmpIntf.NldInfoOrBuilder getNldInfoOrBuilder() {
      return nldInfo_;
    }

    /**
     * <code>optional .PageInfo page_info = 3;</code>
     */
    public boolean hasPageInfo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }

    /**
     * <code>optional .PageInfo page_info = 3;</code>
     */
    public com.example.dto.DmpIntf.PageInfo getPageInfo() {
      return pageInfo_;
    }

    /**
     * <code>optional .PageInfo page_info = 3;</code>
     */
    public com.example.dto.DmpIntf.PageInfoOrBuilder getPageInfoOrBuilder() {
      return pageInfo_;
    }

    /**
     * <code>optional .AppInfo app_info = 4;</code>
     */
    public boolean hasAppInfo() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }

    /**
     * <code>optional .AppInfo app_info = 4;</code>
     */
    public com.example.dto.DmpIntf.AppInfo getAppInfo() {
      return appInfo_;
    }

    /**
     * <code>optional .AppInfo app_info = 4;</code>
     */
    public com.example.dto.DmpIntf.AppInfoOrBuilder getAppInfoOrBuilder() {
      return appInfo_;
    }

    /**
     * <code>optional uint64 transaction_id = 5;</code>
     */
    public boolean hasTransactionId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }

    /**
     * <code>optional uint64 transaction_id = 5;</code>
     */
    public long getTransactionId() {
      return transactionId_;
    }

    /**
     * <code>optional uint64 source_instance_id = 6;</code>
     */
    public boolean hasSourceInstanceId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }

    /**
     * <code>optional uint64 source_instance_id = 6;</code>
     */
    public long getSourceInstanceId() {
      return sourceInstanceId_;
    }

    /**
     * <code>optional uint64 timestamp = 7;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }

    /**
     * <code>optional uint64 timestamp = 7;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      tldInfo_ = com.example.dto.DmpIntf.TldInfo.getDefaultInstance();
      nldInfo_ = com.example.dto.DmpIntf.NldInfo.getDefaultInstance();
      pageInfo_ = com.example.dto.DmpIntf.PageInfo.getDefaultInstance();
      appInfo_ = com.example.dto.DmpIntf.AppInfo.getDefaultInstance();
      transactionId_ = 0L;
      sourceInstanceId_ = 0L;
      timestamp_ = 0L;
    }

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, tldInfo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, nldInfo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, pageInfo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, appInfo_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(5, transactionId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(6, sourceInstanceId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt64(7, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, tldInfo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, nldInfo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, pageInfo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, appInfo_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, transactionId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, sourceInstanceId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    @Override
    protected Object writeReplace()
      throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public Builder newBuilderForType() { return newBuilder(); }

    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
      BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code BidMetaEntityMessage}
     */
    public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BidMetaEntityMessage)
      BidMetaEntityMessageOrBuilder {
      private int bitField0_;
      private com.example.dto.DmpIntf.TldInfo tldInfo_ =
        com.example.dto.DmpIntf.TldInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
        com.example.dto.DmpIntf.TldInfo, com.example.dto.DmpIntf.TldInfo.Builder, com.example.dto.DmpIntf.TldInfoOrBuilder>
        tldInfoBuilder_;
      private com.example.dto.DmpIntf.NldInfo nldInfo_ =
        com.example.dto.DmpIntf.NldInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
        com.example.dto.DmpIntf.NldInfo, com.example.dto.DmpIntf.NldInfo.Builder, com.example.dto.DmpIntf.NldInfoOrBuilder>
        nldInfoBuilder_;
      private com.example.dto.DmpIntf.PageInfo pageInfo_ =
        com.example.dto.DmpIntf.PageInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
        com.example.dto.DmpIntf.PageInfo, com.example.dto.DmpIntf.PageInfo.Builder, com.example.dto.DmpIntf.PageInfoOrBuilder>
        pageInfoBuilder_;
      private com.example.dto.DmpIntf.AppInfo appInfo_ =
        com.example.dto.DmpIntf.AppInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
        com.example.dto.DmpIntf.AppInfo, com.example.dto.DmpIntf.AppInfo.Builder, com.example.dto.DmpIntf.AppInfoOrBuilder>
        appInfoBuilder_;
      private long transactionId_;
      private long sourceInstanceId_;
      private long timestamp_;

      // Construct using com.example.dto.BidMetaEntity.BidMetaEntityMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
        BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return BidMetaEntity.internal_static_BidMetaEntityMessage_descriptor;
      }

      private static Builder create() {
        return new Builder();
      }

      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return BidMetaEntity.internal_static_BidMetaEntityMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
            BidMetaEntityMessage.class, Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTldInfoFieldBuilder();
          getNldInfoFieldBuilder();
          getPageInfoFieldBuilder();
          getAppInfoFieldBuilder();
        }
      }

      public Builder clear() {
        super.clear();
        if (tldInfoBuilder_ == null) {
          tldInfo_ = com.example.dto.DmpIntf.TldInfo.getDefaultInstance();
        } else {
          tldInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (nldInfoBuilder_ == null) {
          nldInfo_ = com.example.dto.DmpIntf.NldInfo.getDefaultInstance();
        } else {
          nldInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (pageInfoBuilder_ == null) {
          pageInfo_ = com.example.dto.DmpIntf.PageInfo.getDefaultInstance();
        } else {
          pageInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (appInfoBuilder_ == null) {
          appInfo_ = com.example.dto.DmpIntf.AppInfo.getDefaultInstance();
        } else {
          appInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        transactionId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        sourceInstanceId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return BidMetaEntity.internal_static_BidMetaEntityMessage_descriptor;
      }

      public BidMetaEntityMessage getDefaultInstanceForType() {
        return BidMetaEntityMessage.getDefaultInstance();
      }

      public BidMetaEntityMessage build() {
        BidMetaEntityMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BidMetaEntityMessage buildPartial() {
        BidMetaEntityMessage result = new BidMetaEntityMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (tldInfoBuilder_ == null) {
          result.tldInfo_ = tldInfo_;
        } else {
          result.tldInfo_ = tldInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (nldInfoBuilder_ == null) {
          result.nldInfo_ = nldInfo_;
        } else {
          result.nldInfo_ = nldInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (pageInfoBuilder_ == null) {
          result.pageInfo_ = pageInfo_;
        } else {
          result.pageInfo_ = pageInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (appInfoBuilder_ == null) {
          result.appInfo_ = appInfo_;
        } else {
          result.appInfo_ = appInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.transactionId_ = transactionId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sourceInstanceId_ = sourceInstanceId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BidMetaEntityMessage) {
          return mergeFrom((BidMetaEntityMessage) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BidMetaEntityMessage other) {
        if (other == BidMetaEntityMessage.getDefaultInstance()) return this;
        if (other.hasTldInfo()) {
          mergeTldInfo(other.getTldInfo());
        }
        if (other.hasNldInfo()) {
          mergeNldInfo(other.getNldInfo());
        }
        if (other.hasPageInfo()) {
          mergePageInfo(other.getPageInfo());
        }
        if (other.hasAppInfo()) {
          mergeAppInfo(other.getAppInfo());
        }
        if (other.hasTransactionId()) {
          setTransactionId(other.getTransactionId());
        }
        if (other.hasSourceInstanceId()) {
          setSourceInstanceId(other.getSourceInstanceId());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        BidMetaEntityMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BidMetaEntityMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /**
       * <code>optional .TldInfo tld_info = 1;</code>
       */
      public boolean hasTldInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }

      /**
       * <code>optional .TldInfo tld_info = 1;</code>
       */
      public com.example.dto.DmpIntf.TldInfo getTldInfo() {
        if (tldInfoBuilder_ == null) {
          return tldInfo_;
        } else {
          return tldInfoBuilder_.getMessage();
        }
      }

      /**
       * <code>optional .TldInfo tld_info = 1;</code>
       */
      public Builder setTldInfo(com.example.dto.DmpIntf.TldInfo value) {
        if (tldInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          tldInfo_ = value;
          onChanged();
        } else {
          tldInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }

      /**
       * <code>optional .TldInfo tld_info = 1;</code>
       */
      public Builder setTldInfo(
        com.example.dto.DmpIntf.TldInfo.Builder builderForValue) {
        if (tldInfoBuilder_ == null) {
          tldInfo_ = builderForValue.build();
          onChanged();
        } else {
          tldInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }

      /**
       * <code>optional .TldInfo tld_info = 1;</code>
       */
      public Builder mergeTldInfo(com.example.dto.DmpIntf.TldInfo value) {
        if (tldInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
            tldInfo_ != com.example.dto.DmpIntf.TldInfo.getDefaultInstance()) {
            tldInfo_ =
              com.example.dto.DmpIntf.TldInfo
                .newBuilder(tldInfo_)
                .mergeFrom(value)
                .buildPartial();
          } else {
            tldInfo_ = value;
          }
          onChanged();
        } else {
          tldInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }

      /**
       * <code>optional .TldInfo tld_info = 1;</code>
       */
      public Builder clearTldInfo() {
        if (tldInfoBuilder_ == null) {
          tldInfo_ = com.example.dto.DmpIntf.TldInfo.getDefaultInstance();
          onChanged();
        } else {
          tldInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      /**
       * <code>optional .TldInfo tld_info = 1;</code>
       */
      public com.example.dto.DmpIntf.TldInfo.Builder getTldInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTldInfoFieldBuilder().getBuilder();
      }

      /**
       * <code>optional .TldInfo tld_info = 1;</code>
       */
      public com.example.dto.DmpIntf.TldInfoOrBuilder getTldInfoOrBuilder() {
        if (tldInfoBuilder_ != null) {
          return tldInfoBuilder_.getMessageOrBuilder();
        } else {
          return tldInfo_;
        }
      }

      /**
       * <code>optional .TldInfo tld_info = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
        com.example.dto.DmpIntf.TldInfo, com.example.dto.DmpIntf.TldInfo.Builder, com.example.dto.DmpIntf.TldInfoOrBuilder>
      getTldInfoFieldBuilder() {
        if (tldInfoBuilder_ == null) {
          tldInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.example.dto.DmpIntf.TldInfo, com.example.dto.DmpIntf.TldInfo.Builder, com.example.dto.DmpIntf.TldInfoOrBuilder>(
            getTldInfo(),
            getParentForChildren(),
            isClean());
          tldInfo_ = null;
        }
        return tldInfoBuilder_;
      }

      /**
       * <code>optional .NldInfo nld_info = 2;</code>
       */
      public boolean hasNldInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }

      /**
       * <code>optional .NldInfo nld_info = 2;</code>
       */
      public com.example.dto.DmpIntf.NldInfo getNldInfo() {
        if (nldInfoBuilder_ == null) {
          return nldInfo_;
        } else {
          return nldInfoBuilder_.getMessage();
        }
      }

      /**
       * <code>optional .NldInfo nld_info = 2;</code>
       */
      public Builder setNldInfo(com.example.dto.DmpIntf.NldInfo value) {
        if (nldInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          nldInfo_ = value;
          onChanged();
        } else {
          nldInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }

      /**
       * <code>optional .NldInfo nld_info = 2;</code>
       */
      public Builder setNldInfo(
        com.example.dto.DmpIntf.NldInfo.Builder builderForValue) {
        if (nldInfoBuilder_ == null) {
          nldInfo_ = builderForValue.build();
          onChanged();
        } else {
          nldInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }

      /**
       * <code>optional .NldInfo nld_info = 2;</code>
       */
      public Builder mergeNldInfo(com.example.dto.DmpIntf.NldInfo value) {
        if (nldInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
            nldInfo_ != com.example.dto.DmpIntf.NldInfo.getDefaultInstance()) {
            nldInfo_ =
              com.example.dto.DmpIntf.NldInfo
                .newBuilder(nldInfo_)
                .mergeFrom(value)
                .buildPartial();
          } else {
            nldInfo_ = value;
          }
          onChanged();
        } else {
          nldInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }

      /**
       * <code>optional .NldInfo nld_info = 2;</code>
       */
      public Builder clearNldInfo() {
        if (nldInfoBuilder_ == null) {
          nldInfo_ = com.example.dto.DmpIntf.NldInfo.getDefaultInstance();
          onChanged();
        } else {
          nldInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      /**
       * <code>optional .NldInfo nld_info = 2;</code>
       */
      public com.example.dto.DmpIntf.NldInfo.Builder getNldInfoBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getNldInfoFieldBuilder().getBuilder();
      }

      /**
       * <code>optional .NldInfo nld_info = 2;</code>
       */
      public com.example.dto.DmpIntf.NldInfoOrBuilder getNldInfoOrBuilder() {
        if (nldInfoBuilder_ != null) {
          return nldInfoBuilder_.getMessageOrBuilder();
        } else {
          return nldInfo_;
        }
      }

      /**
       * <code>optional .NldInfo nld_info = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
        com.example.dto.DmpIntf.NldInfo, com.example.dto.DmpIntf.NldInfo.Builder, com.example.dto.DmpIntf.NldInfoOrBuilder>
      getNldInfoFieldBuilder() {
        if (nldInfoBuilder_ == null) {
          nldInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.example.dto.DmpIntf.NldInfo, com.example.dto.DmpIntf.NldInfo.Builder, com.example.dto.DmpIntf.NldInfoOrBuilder>(
            getNldInfo(),
            getParentForChildren(),
            isClean());
          nldInfo_ = null;
        }
        return nldInfoBuilder_;
      }

      /**
       * <code>optional .PageInfo page_info = 3;</code>
       */
      public boolean hasPageInfo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }

      /**
       * <code>optional .PageInfo page_info = 3;</code>
       */
      public com.example.dto.DmpIntf.PageInfo getPageInfo() {
        if (pageInfoBuilder_ == null) {
          return pageInfo_;
        } else {
          return pageInfoBuilder_.getMessage();
        }
      }

      /**
       * <code>optional .PageInfo page_info = 3;</code>
       */
      public Builder setPageInfo(com.example.dto.DmpIntf.PageInfo value) {
        if (pageInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pageInfo_ = value;
          onChanged();
        } else {
          pageInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }

      /**
       * <code>optional .PageInfo page_info = 3;</code>
       */
      public Builder setPageInfo(
        com.example.dto.DmpIntf.PageInfo.Builder builderForValue) {
        if (pageInfoBuilder_ == null) {
          pageInfo_ = builderForValue.build();
          onChanged();
        } else {
          pageInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }

      /**
       * <code>optional .PageInfo page_info = 3;</code>
       */
      public Builder mergePageInfo(com.example.dto.DmpIntf.PageInfo value) {
        if (pageInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
            pageInfo_ != com.example.dto.DmpIntf.PageInfo.getDefaultInstance()) {
            pageInfo_ =
              com.example.dto.DmpIntf.PageInfo
                .newBuilder(pageInfo_)
                .mergeFrom(value)
                .buildPartial();
          } else {
            pageInfo_ = value;
          }
          onChanged();
        } else {
          pageInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }

      /**
       * <code>optional .PageInfo page_info = 3;</code>
       */
      public Builder clearPageInfo() {
        if (pageInfoBuilder_ == null) {
          pageInfo_ = com.example.dto.DmpIntf.PageInfo.getDefaultInstance();
          onChanged();
        } else {
          pageInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      /**
       * <code>optional .PageInfo page_info = 3;</code>
       */
      public com.example.dto.DmpIntf.PageInfo.Builder getPageInfoBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getPageInfoFieldBuilder().getBuilder();
      }

      /**
       * <code>optional .PageInfo page_info = 3;</code>
       */
      public com.example.dto.DmpIntf.PageInfoOrBuilder getPageInfoOrBuilder() {
        if (pageInfoBuilder_ != null) {
          return pageInfoBuilder_.getMessageOrBuilder();
        } else {
          return pageInfo_;
        }
      }

      /**
       * <code>optional .PageInfo page_info = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
        com.example.dto.DmpIntf.PageInfo, com.example.dto.DmpIntf.PageInfo.Builder, com.example.dto.DmpIntf.PageInfoOrBuilder>
      getPageInfoFieldBuilder() {
        if (pageInfoBuilder_ == null) {
          pageInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.example.dto.DmpIntf.PageInfo, com.example.dto.DmpIntf.PageInfo.Builder, com.example.dto.DmpIntf.PageInfoOrBuilder>(
            getPageInfo(),
            getParentForChildren(),
            isClean());
          pageInfo_ = null;
        }
        return pageInfoBuilder_;
      }

      /**
       * <code>optional .AppInfo app_info = 4;</code>
       */
      public boolean hasAppInfo() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }

      /**
       * <code>optional .AppInfo app_info = 4;</code>
       */
      public com.example.dto.DmpIntf.AppInfo getAppInfo() {
        if (appInfoBuilder_ == null) {
          return appInfo_;
        } else {
          return appInfoBuilder_.getMessage();
        }
      }

      /**
       * <code>optional .AppInfo app_info = 4;</code>
       */
      public Builder setAppInfo(com.example.dto.DmpIntf.AppInfo value) {
        if (appInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          appInfo_ = value;
          onChanged();
        } else {
          appInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }

      /**
       * <code>optional .AppInfo app_info = 4;</code>
       */
      public Builder setAppInfo(
        com.example.dto.DmpIntf.AppInfo.Builder builderForValue) {
        if (appInfoBuilder_ == null) {
          appInfo_ = builderForValue.build();
          onChanged();
        } else {
          appInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }

      /**
       * <code>optional .AppInfo app_info = 4;</code>
       */
      public Builder mergeAppInfo(com.example.dto.DmpIntf.AppInfo value) {
        if (appInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
            appInfo_ != com.example.dto.DmpIntf.AppInfo.getDefaultInstance()) {
            appInfo_ =
              com.example.dto.DmpIntf.AppInfo
                .newBuilder(appInfo_)
                .mergeFrom(value)
                .buildPartial();
          } else {
            appInfo_ = value;
          }
          onChanged();
        } else {
          appInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }

      /**
       * <code>optional .AppInfo app_info = 4;</code>
       */
      public Builder clearAppInfo() {
        if (appInfoBuilder_ == null) {
          appInfo_ = com.example.dto.DmpIntf.AppInfo.getDefaultInstance();
          onChanged();
        } else {
          appInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      /**
       * <code>optional .AppInfo app_info = 4;</code>
       */
      public com.example.dto.DmpIntf.AppInfo.Builder getAppInfoBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getAppInfoFieldBuilder().getBuilder();
      }

      /**
       * <code>optional .AppInfo app_info = 4;</code>
       */
      public com.example.dto.DmpIntf.AppInfoOrBuilder getAppInfoOrBuilder() {
        if (appInfoBuilder_ != null) {
          return appInfoBuilder_.getMessageOrBuilder();
        } else {
          return appInfo_;
        }
      }

      /**
       * <code>optional .AppInfo app_info = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
        com.example.dto.DmpIntf.AppInfo, com.example.dto.DmpIntf.AppInfo.Builder, com.example.dto.DmpIntf.AppInfoOrBuilder>
      getAppInfoFieldBuilder() {
        if (appInfoBuilder_ == null) {
          appInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.example.dto.DmpIntf.AppInfo, com.example.dto.DmpIntf.AppInfo.Builder, com.example.dto.DmpIntf.AppInfoOrBuilder>(
            getAppInfo(),
            getParentForChildren(),
            isClean());
          appInfo_ = null;
        }
        return appInfoBuilder_;
      }

      /**
       * <code>optional uint64 transaction_id = 5;</code>
       */
      public boolean hasTransactionId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }

      /**
       * <code>optional uint64 transaction_id = 5;</code>
       */
      public long getTransactionId() {
        return transactionId_;
      }

      /**
       * <code>optional uint64 transaction_id = 5;</code>
       */
      public Builder setTransactionId(long value) {
        bitField0_ |= 0x00000010;
        transactionId_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional uint64 transaction_id = 5;</code>
       */
      public Builder clearTransactionId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        transactionId_ = 0L;
        onChanged();
        return this;
      }

      /**
       * <code>optional uint64 source_instance_id = 6;</code>
       */
      public boolean hasSourceInstanceId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }

      /**
       * <code>optional uint64 source_instance_id = 6;</code>
       */
      public long getSourceInstanceId() {
        return sourceInstanceId_;
      }

      /**
       * <code>optional uint64 source_instance_id = 6;</code>
       */
      public Builder setSourceInstanceId(long value) {
        bitField0_ |= 0x00000020;
        sourceInstanceId_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional uint64 source_instance_id = 6;</code>
       */
      public Builder clearSourceInstanceId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sourceInstanceId_ = 0L;
        onChanged();
        return this;
      }

      /**
       * <code>optional uint64 timestamp = 7;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }

      /**
       * <code>optional uint64 timestamp = 7;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }

      /**
       * <code>optional uint64 timestamp = 7;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000040;
        timestamp_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional uint64 timestamp = 7;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000040);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BidMetaEntityMessage)
    }

    // @@protoc_insertion_point(class_scope:BidMetaEntityMessage)
  }

  // @@protoc_insertion_point(outer_class_scope)
}
