// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cnr.proto

package com.example.dto;

public final class Cnr {
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CnrProtoMsg_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internal_static_CnrProtoMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
    descriptor;

  static {
    String[] descriptorData = {
      "\n\tcnr.proto\032\016dmp_intf.proto\032\025bid_meta_en" +
        "tity.proto\"\226\001\n\013CnrProtoMsg\022\021\n\tsignature\030" +
        "\001 \002(\r\022\r\n\005proto\030\002 \002(\r\022\017\n\007version\030\003 \002(\r\022\r\n" +
        "\005flags\030\004 \002(\r\022\030\n\007dmp_msg\030) \001(\0132\007.DmpMsg\022+" +
        "\n\014bid_meta_msg\030* \001(\0132\025.BidMetaEntityMess" +
        "age*7\n\010CnrProto\022\022\n\rCNR_PROTO_DMP\020\216\002\022\027\n\022C" +
        "NR_PROTO_BID_META\020\217\002B+\n\037com.cinarra.bidp" +
        "ersister.domainZ\010cnrproto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
          com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.dto.DmpIntf.getDescriptor(),
          BidMetaEntity.getDescriptor(),
        }, assigner);
    internal_static_CnrProtoMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CnrProtoMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
      internal_static_CnrProtoMsg_descriptor,
      new String[] {"Signature", "Proto", "Version", "Flags", "DmpMsg", "BidMetaMsg",});
    com.example.dto.DmpIntf.getDescriptor();
    BidMetaEntity.getDescriptor();
  }

  private Cnr() {}

  public static void registerAllExtensions(
    com.google.protobuf.ExtensionRegistry registry) {
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  /**
   * Protobuf enum {@code CnrProto}
   */
  public enum CnrProto
    implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CNR_PROTO_DMP = 270;</code>
     *
     * <pre>
     * Interface messages to Cinarra DMP
     * </pre>
     */
    CNR_PROTO_DMP(0, 270),
    /**
     * <code>CNR_PROTO_BID_META = 271;</code>
     *
     * <pre>
     * Message containing meta-data(categories) information of Site/App
     * </pre>
     */
    CNR_PROTO_BID_META(1, 271),
    ;

    /**
     * <code>CNR_PROTO_DMP = 270;</code>
     *
     * <pre>
     * Interface messages to Cinarra DMP
     * </pre>
     */
    public static final int CNR_PROTO_DMP_VALUE = 270;
    /**
     * <code>CNR_PROTO_BID_META = 271;</code>
     *
     * <pre>
     * Message containing meta-data(categories) information of Site/App
     * </pre>
     */
    public static final int CNR_PROTO_BID_META_VALUE = 271;
    private static final CnrProto[] VALUES = values();
    private static com.google.protobuf.Internal.EnumLiteMap<CnrProto>
      internalValueMap =
      new com.google.protobuf.Internal.EnumLiteMap<CnrProto>() {
        public CnrProto findValueByNumber(int number) {
          return CnrProto.valueOf(number);
        }
      };
    private final int index;
    private final int value;

    private CnrProto(int index, int value) {
      this.index = index;
      this.value = value;
    }

    public static CnrProto valueOf(int value) {
      switch (value) {
        case 270:
          return CNR_PROTO_DMP;
        case 271:
          return CNR_PROTO_BID_META;
        default:
          return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CnrProto>
    internalGetValueMap() {
      return internalValueMap;
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
      return Cnr.getDescriptor().getEnumTypes().get(0);
    }

    public static CnrProto valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    public final int getNumber() { return value; }

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
      return getDescriptor();
    }

    // @@protoc_insertion_point(enum_scope:CnrProto)
  }

  public interface CnrProtoMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CnrProtoMsg)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 signature = 1;</code>
     *
     * <pre>
     * Magic value defined in cproto.h
     * </pre>
     */
    boolean hasSignature();

    /**
     * <code>required uint32 signature = 1;</code>
     *
     * <pre>
     * Magic value defined in cproto.h
     * </pre>
     */
    int getSignature();

    /**
     * <code>required uint32 proto = 2;</code>
     *
     * <pre>
     * CNR_PROTO_XXX values in cproto.h
     * </pre>
     */
    boolean hasProto();

    /**
     * <code>required uint32 proto = 2;</code>
     *
     * <pre>
     * CNR_PROTO_XXX values in cproto.h
     * </pre>
     */
    int getProto();

    /**
     * <code>required uint32 version = 3;</code>
     *
     * <pre>
     * CNR_PROTO_XXX_CURR_VERSION values in cproto.h
     * </pre>
     */
    boolean hasVersion();

    /**
     * <code>required uint32 version = 3;</code>
     *
     * <pre>
     * CNR_PROTO_XXX_CURR_VERSION values in cproto.h
     * </pre>
     */
    int getVersion();

    /**
     * <code>required uint32 flags = 4;</code>
     *
     * <pre>
     * CNR_PROTO_FLG_XXX values in cproto.h
     * </pre>
     */
    boolean hasFlags();

    /**
     * <code>required uint32 flags = 4;</code>
     *
     * <pre>
     * CNR_PROTO_FLG_XXX values in cproto.h
     * </pre>
     */
    int getFlags();

    /**
     * <code>optional .DmpMsg dmp_msg = 41;</code>
     *
     * <pre>
     * One of the following messages depending on the proto field value
     * </pre>
     */
    boolean hasDmpMsg();

    /**
     * <code>optional .DmpMsg dmp_msg = 41;</code>
     *
     * <pre>
     * One of the following messages depending on the proto field value
     * </pre>
     */
    com.example.dto.DmpIntf.DmpMsg getDmpMsg();

    /**
     * <code>optional .DmpMsg dmp_msg = 41;</code>
     *
     * <pre>
     * One of the following messages depending on the proto field value
     * </pre>
     */
    com.example.dto.DmpIntf.DmpMsgOrBuilder getDmpMsgOrBuilder();

    /**
     * <code>optional .BidMetaEntityMessage bid_meta_msg = 42;</code>
     */
    boolean hasBidMetaMsg();

    /**
     * <code>optional .BidMetaEntityMessage bid_meta_msg = 42;</code>
     */
    BidMetaEntity.BidMetaEntityMessage getBidMetaMsg();

    /**
     * <code>optional .BidMetaEntityMessage bid_meta_msg = 42;</code>
     */
    BidMetaEntity.BidMetaEntityMessageOrBuilder getBidMetaMsgOrBuilder();
  }

  /**
   * Protobuf type {@code CnrProtoMsg}
   *
   * <pre>
   * Unique Transaction ID
   * </pre>
   */
  public static final class CnrProtoMsg extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:CnrProtoMsg)
    CnrProtoMsgOrBuilder {
    public static final int SIGNATURE_FIELD_NUMBER = 1;
    public static final int PROTO_FIELD_NUMBER = 2;
    public static final int VERSION_FIELD_NUMBER = 3;
    public static final int FLAGS_FIELD_NUMBER = 4;
    public static final int DMP_MSG_FIELD_NUMBER = 41;
    public static final int BID_META_MSG_FIELD_NUMBER = 42;
    private static final CnrProtoMsg defaultInstance;
    private static final long serialVersionUID = 0L;
    public static com.google.protobuf.Parser<CnrProtoMsg> PARSER =
      new com.google.protobuf.AbstractParser<CnrProtoMsg>() {
        public CnrProtoMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CnrProtoMsg(input, extensionRegistry);
        }
      };

    static {
      defaultInstance = new CnrProtoMsg(true);
      defaultInstance.initFields();
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    private int bitField0_;
    private int signature_;
    private int proto_;
    private int version_;
    private int flags_;
    private com.example.dto.DmpIntf.DmpMsg dmpMsg_;
    private BidMetaEntity.BidMetaEntityMessage bidMetaMsg_;
    private byte memoizedIsInitialized = -1;
    private int memoizedSerializedSize = -1;

    // Use CnrProtoMsg.newBuilder() to construct.
    private CnrProtoMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }

    private CnrProtoMsg(boolean noInit) {
      this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CnrProtoMsg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              signature_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              proto_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              version_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              flags_ = input.readUInt32();
              break;
            }
            case 330: {
              com.example.dto.DmpIntf.DmpMsg.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = dmpMsg_.toBuilder();
              }
              dmpMsg_ = input.readMessage(
                com.example.dto.DmpIntf.DmpMsg.PARSER,
                extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dmpMsg_);
                dmpMsg_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 338: {
              BidMetaEntity.BidMetaEntityMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = bidMetaMsg_.toBuilder();
              }
              bidMetaMsg_ =
                input.readMessage(BidMetaEntity.BidMetaEntityMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bidMetaMsg_);
                bidMetaMsg_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static CnrProtoMsg getDefaultInstance() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return Cnr.internal_static_CnrProtoMsg_descriptor;
    }

    public static CnrProtoMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static CnrProtoMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static CnrProtoMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static CnrProtoMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static CnrProtoMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static CnrProtoMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static CnrProtoMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }

    public static CnrProtoMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static CnrProtoMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static CnrProtoMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }

    public static Builder newBuilder(CnrProtoMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }

    public CnrProtoMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return Cnr.internal_static_CnrProtoMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
          CnrProtoMsg.class, Builder.class);
    }

    @Override
    public com.google.protobuf.Parser<CnrProtoMsg> getParserForType() {
      return PARSER;
    }

    /**
     * <code>required uint32 signature = 1;</code>
     *
     * <pre>
     * Magic value defined in cproto.h
     * </pre>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }

    /**
     * <code>required uint32 signature = 1;</code>
     *
     * <pre>
     * Magic value defined in cproto.h
     * </pre>
     */
    public int getSignature() {
      return signature_;
    }

    /**
     * <code>required uint32 proto = 2;</code>
     *
     * <pre>
     * CNR_PROTO_XXX values in cproto.h
     * </pre>
     */
    public boolean hasProto() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }

    /**
     * <code>required uint32 proto = 2;</code>
     *
     * <pre>
     * CNR_PROTO_XXX values in cproto.h
     * </pre>
     */
    public int getProto() {
      return proto_;
    }

    /**
     * <code>required uint32 version = 3;</code>
     *
     * <pre>
     * CNR_PROTO_XXX_CURR_VERSION values in cproto.h
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }

    /**
     * <code>required uint32 version = 3;</code>
     *
     * <pre>
     * CNR_PROTO_XXX_CURR_VERSION values in cproto.h
     * </pre>
     */
    public int getVersion() {
      return version_;
    }

    /**
     * <code>required uint32 flags = 4;</code>
     *
     * <pre>
     * CNR_PROTO_FLG_XXX values in cproto.h
     * </pre>
     */
    public boolean hasFlags() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }

    /**
     * <code>required uint32 flags = 4;</code>
     *
     * <pre>
     * CNR_PROTO_FLG_XXX values in cproto.h
     * </pre>
     */
    public int getFlags() {
      return flags_;
    }

    /**
     * <code>optional .DmpMsg dmp_msg = 41;</code>
     *
     * <pre>
     * One of the following messages depending on the proto field value
     * </pre>
     */
    public boolean hasDmpMsg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }

    /**
     * <code>optional .DmpMsg dmp_msg = 41;</code>
     *
     * <pre>
     * One of the following messages depending on the proto field value
     * </pre>
     */
    public com.example.dto.DmpIntf.DmpMsg getDmpMsg() {
      return dmpMsg_;
    }

    /**
     * <code>optional .DmpMsg dmp_msg = 41;</code>
     *
     * <pre>
     * One of the following messages depending on the proto field value
     * </pre>
     */
    public com.example.dto.DmpIntf.DmpMsgOrBuilder getDmpMsgOrBuilder() {
      return dmpMsg_;
    }

    /**
     * <code>optional .BidMetaEntityMessage bid_meta_msg = 42;</code>
     */
    public boolean hasBidMetaMsg() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }

    /**
     * <code>optional .BidMetaEntityMessage bid_meta_msg = 42;</code>
     */
    public BidMetaEntity.BidMetaEntityMessage getBidMetaMsg() {
      return bidMetaMsg_;
    }

    /**
     * <code>optional .BidMetaEntityMessage bid_meta_msg = 42;</code>
     */
    public BidMetaEntity.BidMetaEntityMessageOrBuilder getBidMetaMsgOrBuilder() {
      return bidMetaMsg_;
    }

    private void initFields() {
      signature_ = 0;
      proto_ = 0;
      version_ = 0;
      flags_ = 0;
      dmpMsg_ = com.example.dto.DmpIntf.DmpMsg.getDefaultInstance();
      bidMetaMsg_ = BidMetaEntity.BidMetaEntityMessage.getDefaultInstance();
    }

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSignature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProto()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFlags()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, signature_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, proto_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, flags_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(41, dmpMsg_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(42, bidMetaMsg_);
      }
      getUnknownFields().writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, signature_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, proto_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, flags_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(41, dmpMsg_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(42, bidMetaMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    @Override
    protected Object writeReplace()
      throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public Builder newBuilderForType() { return newBuilder(); }

    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
      BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code CnrProtoMsg}
     *
     * <pre>
     * Unique Transaction ID
     * </pre>
     */
    public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CnrProtoMsg)
      CnrProtoMsgOrBuilder {
      private int bitField0_;
      private int signature_;
      private int proto_;
      private int version_;
      private int flags_;
      private com.example.dto.DmpIntf.DmpMsg dmpMsg_ =
        com.example.dto.DmpIntf.DmpMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
        com.example.dto.DmpIntf.DmpMsg, com.example.dto.DmpIntf.DmpMsg.Builder, com.example.dto.DmpIntf.DmpMsgOrBuilder>
        dmpMsgBuilder_;
      private BidMetaEntity.BidMetaEntityMessage bidMetaMsg_ =
        BidMetaEntity.BidMetaEntityMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
        BidMetaEntity.BidMetaEntityMessage, BidMetaEntity.BidMetaEntityMessage.Builder, BidMetaEntity.BidMetaEntityMessageOrBuilder>
        bidMetaMsgBuilder_;

      // Construct using com.example.dto.Cnr.CnrProtoMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
        BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return Cnr.internal_static_CnrProtoMsg_descriptor;
      }

      private static Builder create() {
        return new Builder();
      }

      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return Cnr.internal_static_CnrProtoMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
            CnrProtoMsg.class, Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDmpMsgFieldBuilder();
          getBidMetaMsgFieldBuilder();
        }
      }

      public Builder clear() {
        super.clear();
        signature_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        proto_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        flags_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (dmpMsgBuilder_ == null) {
          dmpMsg_ = com.example.dto.DmpIntf.DmpMsg.getDefaultInstance();
        } else {
          dmpMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (bidMetaMsgBuilder_ == null) {
          bidMetaMsg_ = BidMetaEntity.BidMetaEntityMessage.getDefaultInstance();
        } else {
          bidMetaMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return Cnr.internal_static_CnrProtoMsg_descriptor;
      }

      public CnrProtoMsg getDefaultInstanceForType() {
        return CnrProtoMsg.getDefaultInstance();
      }

      public CnrProtoMsg build() {
        CnrProtoMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CnrProtoMsg buildPartial() {
        CnrProtoMsg result = new CnrProtoMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.signature_ = signature_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.proto_ = proto_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.flags_ = flags_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (dmpMsgBuilder_ == null) {
          result.dmpMsg_ = dmpMsg_;
        } else {
          result.dmpMsg_ = dmpMsgBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (bidMetaMsgBuilder_ == null) {
          result.bidMetaMsg_ = bidMetaMsg_;
        } else {
          result.bidMetaMsg_ = bidMetaMsgBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CnrProtoMsg) {
          return mergeFrom((CnrProtoMsg) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CnrProtoMsg other) {
        if (other == CnrProtoMsg.getDefaultInstance()) return this;
        if (other.hasSignature()) {
          setSignature(other.getSignature());
        }
        if (other.hasProto()) {
          setProto(other.getProto());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasFlags()) {
          setFlags(other.getFlags());
        }
        if (other.hasDmpMsg()) {
          mergeDmpMsg(other.getDmpMsg());
        }
        if (other.hasBidMetaMsg()) {
          mergeBidMetaMsg(other.getBidMetaMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSignature()) {

          return false;
        }
        if (!hasProto()) {

          return false;
        }
        if (!hasVersion()) {

          return false;
        }
        if (!hasFlags()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        CnrProtoMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CnrProtoMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /**
       * <code>required uint32 signature = 1;</code>
       *
       * <pre>
       * Magic value defined in cproto.h
       * </pre>
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }

      /**
       * <code>required uint32 signature = 1;</code>
       *
       * <pre>
       * Magic value defined in cproto.h
       * </pre>
       */
      public int getSignature() {
        return signature_;
      }

      /**
       * <code>required uint32 signature = 1;</code>
       *
       * <pre>
       * Magic value defined in cproto.h
       * </pre>
       */
      public Builder setSignature(int value) {
        bitField0_ |= 0x00000001;
        signature_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required uint32 signature = 1;</code>
       *
       * <pre>
       * Magic value defined in cproto.h
       * </pre>
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000001);
        signature_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>required uint32 proto = 2;</code>
       *
       * <pre>
       * CNR_PROTO_XXX values in cproto.h
       * </pre>
       */
      public boolean hasProto() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }

      /**
       * <code>required uint32 proto = 2;</code>
       *
       * <pre>
       * CNR_PROTO_XXX values in cproto.h
       * </pre>
       */
      public int getProto() {
        return proto_;
      }

      /**
       * <code>required uint32 proto = 2;</code>
       *
       * <pre>
       * CNR_PROTO_XXX values in cproto.h
       * </pre>
       */
      public Builder setProto(int value) {
        bitField0_ |= 0x00000002;
        proto_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required uint32 proto = 2;</code>
       *
       * <pre>
       * CNR_PROTO_XXX values in cproto.h
       * </pre>
       */
      public Builder clearProto() {
        bitField0_ = (bitField0_ & ~0x00000002);
        proto_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>required uint32 version = 3;</code>
       *
       * <pre>
       * CNR_PROTO_XXX_CURR_VERSION values in cproto.h
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }

      /**
       * <code>required uint32 version = 3;</code>
       *
       * <pre>
       * CNR_PROTO_XXX_CURR_VERSION values in cproto.h
       * </pre>
       */
      public int getVersion() {
        return version_;
      }

      /**
       * <code>required uint32 version = 3;</code>
       *
       * <pre>
       * CNR_PROTO_XXX_CURR_VERSION values in cproto.h
       * </pre>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required uint32 version = 3;</code>
       *
       * <pre>
       * CNR_PROTO_XXX_CURR_VERSION values in cproto.h
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>required uint32 flags = 4;</code>
       *
       * <pre>
       * CNR_PROTO_FLG_XXX values in cproto.h
       * </pre>
       */
      public boolean hasFlags() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }

      /**
       * <code>required uint32 flags = 4;</code>
       *
       * <pre>
       * CNR_PROTO_FLG_XXX values in cproto.h
       * </pre>
       */
      public int getFlags() {
        return flags_;
      }

      /**
       * <code>required uint32 flags = 4;</code>
       *
       * <pre>
       * CNR_PROTO_FLG_XXX values in cproto.h
       * </pre>
       */
      public Builder setFlags(int value) {
        bitField0_ |= 0x00000008;
        flags_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required uint32 flags = 4;</code>
       *
       * <pre>
       * CNR_PROTO_FLG_XXX values in cproto.h
       * </pre>
       */
      public Builder clearFlags() {
        bitField0_ = (bitField0_ & ~0x00000008);
        flags_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>optional .DmpMsg dmp_msg = 41;</code>
       *
       * <pre>
       * One of the following messages depending on the proto field value
       * </pre>
       */
      public boolean hasDmpMsg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }

      /**
       * <code>optional .DmpMsg dmp_msg = 41;</code>
       *
       * <pre>
       * One of the following messages depending on the proto field value
       * </pre>
       */
      public com.example.dto.DmpIntf.DmpMsg getDmpMsg() {
        if (dmpMsgBuilder_ == null) {
          return dmpMsg_;
        } else {
          return dmpMsgBuilder_.getMessage();
        }
      }

      /**
       * <code>optional .DmpMsg dmp_msg = 41;</code>
       *
       * <pre>
       * One of the following messages depending on the proto field value
       * </pre>
       */
      public Builder setDmpMsg(com.example.dto.DmpIntf.DmpMsg value) {
        if (dmpMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dmpMsg_ = value;
          onChanged();
        } else {
          dmpMsgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }

      /**
       * <code>optional .DmpMsg dmp_msg = 41;</code>
       *
       * <pre>
       * One of the following messages depending on the proto field value
       * </pre>
       */
      public Builder setDmpMsg(
        com.example.dto.DmpIntf.DmpMsg.Builder builderForValue) {
        if (dmpMsgBuilder_ == null) {
          dmpMsg_ = builderForValue.build();
          onChanged();
        } else {
          dmpMsgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }

      /**
       * <code>optional .DmpMsg dmp_msg = 41;</code>
       *
       * <pre>
       * One of the following messages depending on the proto field value
       * </pre>
       */
      public Builder mergeDmpMsg(com.example.dto.DmpIntf.DmpMsg value) {
        if (dmpMsgBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
            dmpMsg_ != com.example.dto.DmpIntf.DmpMsg.getDefaultInstance()) {
            dmpMsg_ =
              com.example.dto.DmpIntf.DmpMsg
                .newBuilder(dmpMsg_)
                .mergeFrom(value)
                .buildPartial();
          } else {
            dmpMsg_ = value;
          }
          onChanged();
        } else {
          dmpMsgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }

      /**
       * <code>optional .DmpMsg dmp_msg = 41;</code>
       *
       * <pre>
       * One of the following messages depending on the proto field value
       * </pre>
       */
      public Builder clearDmpMsg() {
        if (dmpMsgBuilder_ == null) {
          dmpMsg_ = com.example.dto.DmpIntf.DmpMsg.getDefaultInstance();
          onChanged();
        } else {
          dmpMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      /**
       * <code>optional .DmpMsg dmp_msg = 41;</code>
       *
       * <pre>
       * One of the following messages depending on the proto field value
       * </pre>
       */
      public com.example.dto.DmpIntf.DmpMsg.Builder getDmpMsgBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getDmpMsgFieldBuilder().getBuilder();
      }

      /**
       * <code>optional .DmpMsg dmp_msg = 41;</code>
       *
       * <pre>
       * One of the following messages depending on the proto field value
       * </pre>
       */
      public com.example.dto.DmpIntf.DmpMsgOrBuilder getDmpMsgOrBuilder() {
        if (dmpMsgBuilder_ != null) {
          return dmpMsgBuilder_.getMessageOrBuilder();
        } else {
          return dmpMsg_;
        }
      }

      /**
       * <code>optional .DmpMsg dmp_msg = 41;</code>
       *
       * <pre>
       * One of the following messages depending on the proto field value
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
        com.example.dto.DmpIntf.DmpMsg, com.example.dto.DmpIntf.DmpMsg.Builder, com.example.dto.DmpIntf.DmpMsgOrBuilder>
      getDmpMsgFieldBuilder() {
        if (dmpMsgBuilder_ == null) {
          dmpMsgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.example.dto.DmpIntf.DmpMsg, com.example.dto.DmpIntf.DmpMsg.Builder, com.example.dto.DmpIntf.DmpMsgOrBuilder>(
            getDmpMsg(),
            getParentForChildren(),
            isClean());
          dmpMsg_ = null;
        }
        return dmpMsgBuilder_;
      }

      /**
       * <code>optional .BidMetaEntityMessage bid_meta_msg = 42;</code>
       */
      public boolean hasBidMetaMsg() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }

      /**
       * <code>optional .BidMetaEntityMessage bid_meta_msg = 42;</code>
       */
      public BidMetaEntity.BidMetaEntityMessage getBidMetaMsg() {
        if (bidMetaMsgBuilder_ == null) {
          return bidMetaMsg_;
        } else {
          return bidMetaMsgBuilder_.getMessage();
        }
      }

      /**
       * <code>optional .BidMetaEntityMessage bid_meta_msg = 42;</code>
       */
      public Builder setBidMetaMsg(BidMetaEntity.BidMetaEntityMessage value) {
        if (bidMetaMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bidMetaMsg_ = value;
          onChanged();
        } else {
          bidMetaMsgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }

      /**
       * <code>optional .BidMetaEntityMessage bid_meta_msg = 42;</code>
       */
      public Builder setBidMetaMsg(
        BidMetaEntity.BidMetaEntityMessage.Builder builderForValue) {
        if (bidMetaMsgBuilder_ == null) {
          bidMetaMsg_ = builderForValue.build();
          onChanged();
        } else {
          bidMetaMsgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }

      /**
       * <code>optional .BidMetaEntityMessage bid_meta_msg = 42;</code>
       */
      public Builder mergeBidMetaMsg(BidMetaEntity.BidMetaEntityMessage value) {
        if (bidMetaMsgBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
            bidMetaMsg_ != BidMetaEntity.BidMetaEntityMessage.getDefaultInstance()) {
            bidMetaMsg_ =
              BidMetaEntity.BidMetaEntityMessage
                .newBuilder(bidMetaMsg_)
                .mergeFrom(value)
                .buildPartial();
          } else {
            bidMetaMsg_ = value;
          }
          onChanged();
        } else {
          bidMetaMsgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }

      /**
       * <code>optional .BidMetaEntityMessage bid_meta_msg = 42;</code>
       */
      public Builder clearBidMetaMsg() {
        if (bidMetaMsgBuilder_ == null) {
          bidMetaMsg_ = BidMetaEntity.BidMetaEntityMessage.getDefaultInstance();
          onChanged();
        } else {
          bidMetaMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      /**
       * <code>optional .BidMetaEntityMessage bid_meta_msg = 42;</code>
       */
      public BidMetaEntity.BidMetaEntityMessage.Builder getBidMetaMsgBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getBidMetaMsgFieldBuilder().getBuilder();
      }

      /**
       * <code>optional .BidMetaEntityMessage bid_meta_msg = 42;</code>
       */
      public BidMetaEntity.BidMetaEntityMessageOrBuilder getBidMetaMsgOrBuilder() {
        if (bidMetaMsgBuilder_ != null) {
          return bidMetaMsgBuilder_.getMessageOrBuilder();
        } else {
          return bidMetaMsg_;
        }
      }

      /**
       * <code>optional .BidMetaEntityMessage bid_meta_msg = 42;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
        BidMetaEntity.BidMetaEntityMessage, BidMetaEntity.BidMetaEntityMessage.Builder, BidMetaEntity.BidMetaEntityMessageOrBuilder>
      getBidMetaMsgFieldBuilder() {
        if (bidMetaMsgBuilder_ == null) {
          bidMetaMsgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            BidMetaEntity.BidMetaEntityMessage, BidMetaEntity.BidMetaEntityMessage.Builder, BidMetaEntity.BidMetaEntityMessageOrBuilder>(
            getBidMetaMsg(),
            getParentForChildren(),
            isClean());
          bidMetaMsg_ = null;
        }
        return bidMetaMsgBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:CnrProtoMsg)
    }

    // @@protoc_insertion_point(class_scope:CnrProtoMsg)
  }

  // @@protoc_insertion_point(outer_class_scope)
}
